language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm


matrix:
  allow_failures:
    - php: 5.6
    - hhvm

before_script:
- travis_retry composer self-update
- travis_retry composer install --dev --prefer-source

script: phpunit --coverage-text

notifications:
  email:
    - helios.ag@gmail.com

